services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    ports:
      - "5173:80"

# To run docker compose use: docker-compose up --build
